#!/bin/bash/

if [ -z "$PYFILE" ]; then 
	echo "Error: PYFILE environment varaible is not set"
        exit 1
fi

if [ ! -f "$PYFILE"]; then
	echo "Error: python file '$PYFILE' not found"
	exit 1
fi


python "$PYFILE"
